default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Anshuman@108
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_book_development

 
test:
  <<: *default
  database: recipe_book_test
  username: postgres
  password: Anshuman@108


production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
